name: prova_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  dio: ^5.3.3
  flutter_mobx: ^2.2.0
  mobx: ^2.2.1
  url_launcher: ^6.2.1
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  go_router: ^12.1.1
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
